listener {
  timeout = 10
  on-timeout =  ~/dotfiles/bin/manage_processes.sh suspend vesktop
  on-resume = ~/dotfiles/bin/manage_processes.sh resume vesktop
}

# SLEEP AND LOCK

listener {
  timeout = 300
  on-timeout = ~/dotfiles/bin/manage_processes.sh suspend spotify && ~/dotfiles/bin/lock.sh
  on-resume = ~/dotfiles/bin/manage_processes.sh resume spotify
}

listener {
  timeout = 600
  on-timeout =  /usr/bin/systemctl suspend
}
