listener {
  timeout = 10
  on-timeout =  manage_processes.sh suspend vesktop
  on-resume = manage_processes.sh resume vesktop
}

listener {
  timeout = 300
  on-timeout =  lock.sh && systemctl suspend
}
