alias rsync_backup="rsync -aAXHvP --delete --exclude={
  '/dev/*',
  '/proc/*',
  '/sys/*',
  '/tmp/*',
  '/run/*',
  '/mnt/*',
  '/media/*',
  '/var/cache/*',
  '/var/tmp/*',
  '/var/run/*',
  '/var/lock/*',
  '/lost+found/'} "
alias rsync_backup_root="rsync -aAXHvP --delete --exclude={
  '/dev/*',
  '/proc/*',
  '/sys/*',
  '/tmp/*',
  '/run/*',
  '/mnt/*',
  '/media/*',
  '/var/cache/*',
  '/var/tmp/*',
  '/var/run/*',
  '/var/lock/*',
  '/lost+found/'} "
alias rsync_backup_no_home="rsync -aAXHvP --delete --exclude={
  '/home/*',
  '/dev/*',
  '/proc/*',
  '/sys/*',
  '/tmp/*',
  '/run/*',
  '/mnt/*',
  '/media/*',
  '/var/cache/*',
  '/var/tmp/*',
  '/var/run/*',
  '/var/lock/*',
  '/lost+found/'} "
alias rsync_backup_no_home_root="sudo rsync -aAXHvP --delete --exclude={
  '/home/*',
  '/dev/*',
  '/proc/*',
  '/sys/*',
  '/tmp/*',
  '/run/*',
  '/mnt/*',
  '/media/*',
  '/var/cache/*',
  '/var/tmp/*',
  '/var/run/*',
  '/var/lock/*',
  '/lost+found/'} "

